<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\UniSpace.Bo\UniSpace.BO.csproj" />
		<ProjectReference Include="..\UniSpace.Model\UniSpace.Model.csproj" />
	</ItemGroup>

</Project>
