<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>
	<ItemGroup>
		<Compile Remove="Middlewares\**" />
		<Content Remove="Middlewares\**" />
		<EmbeddedResource Remove="Middlewares\**" />
		<None Remove="Middlewares\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.15">
			<TreatAsUsed>true</TreatAsUsed>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.15">
			<TreatAsUsed>true</TreatAsUsed>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0-preview.4" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.15">
			<TreatAsUsed>true</TreatAsUsed>
		</PackageReference>
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.0">
			<TreatAsUsed>true</TreatAsUsed>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.15">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<TreatAsUsed>true</TreatAsUsed>
		</PackageReference>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2">
			<TreatAsUsed>true</TreatAsUsed>
		</PackageReference>
		<PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.6.2">
			<TreatAsUsed>true</TreatAsUsed>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\UniSpace.Bo\UniSpace.Bo.csproj" />
		<ProjectReference Include="..\Unispace.Service\Unispace.Service.csproj" />
	</ItemGroup>


</Project>
